export const guessGenre = (overlySpecificGenreList: string[]) => {
  const guessedGenre = Object.keys(GENRES).find((key) =>
    GENRES[key].some((subGenre) => overlySpecificGenreList.includes(subGenre))
  )

  return guessedGenre ? guessedGenre : 'unknown'
}

/*
 * The genres here are ones Spotify uses for labeling their artists but they're too specific for me
 * So I guess the broader genre using my own organization
 */
const GENRES: Record<string, string[]> = {
  chinese: [
    'cantopop',
    'chinese electropop',
    'chinese hip hop',
    'chinese idol pop',
    'chinese viral pop',
    'mandopop',
    'taiwan hip hop',
    'taiwan indie',
    'taiwan metal',
    'taiwan pop',
    'taiwan punk',
  ],
  german: [
    'german hip hop',
    'german pop',
    'german reggae',
    'german rock',
    'hamburg hip hop',
    'neue deutsche todeskunst',
  ],
  rock: [
    'alternative metal',
    'folk black metal',
    'future rock',
    'hard rock',
    'industrial metal',
    'industrial rock',
    'nu metal',
    'oriental metal',
    'rap rock',
    'rock',
    'symphonic black metal',
  ],
  club: [
    'big room',
    'breakbeat',
    'brostep',
    'canadian electronic',
    'chillwave',
    'classic dubstep',
    'complextro',
    'croatian electronic',
    'downtempo',
    'drill and bass',
    'dubstep',
    'dutch trance',
    'edm',
    'electro house',
    'electronic trap',
    'experimental bass',
    'fidget house',
    'filthstep',
    'future bass',
    'gaming edm',
    'gauze pop',
    'glitch hop',
    'house',
    'indie dream pop',
    'melodic dubstep',
    'pop',
    'pop dance',
    'progressive house',
    'sky room',
    'trance',
    'trap',
    'tropical house',
    'vapor soul',
    'vapor twitch',
  ],
  ebm: [
    'aggrotech',
    'dark electro',
    'dark electro-industrial',
    'dark wave',
    'ebm',
    'electro-industrial',
    'futurepop',
    'industrial',
    'industrial metal',
    'industrial rock',
    'neo-synthpop',
    'swedish synth',
    'swedish synthpop',
    'synthpop',
  ],
  bitpop: ['balearic', 'bitpop', 'chiptune', 'indietronica', 'nintendocore', 'swedish electropop'],
  synthwave: [
    'chillsynth',
    'cyberpunk',
    'dark clubbing',
    'darksynth',
    'popwave',
    'spacewave',
    'synthwave',
  ],
  misc: [
    'bass',
    'electroclash',
    'experimental',
    'healing',
    'j-metal',
    'japanese metalcore',
    'k-pop',
    'meditation',
    'no genre',
    'otacore',
    'soundtrack',
    'speedrun',
    'tone',
  ],
}
